// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAbfUAjVzz0RkTbcrVyjVxgM6lEOdL5zi8',
    appId: '1:259765583265:web:7e799d0f5613f64b0ddfe0',
    messagingSenderId: '259765583265',
    projectId: 'testdisc-1d691',
    authDomain: 'testdisc-1d691.firebaseapp.com',
    storageBucket: 'testdisc-1d691.firebasestorage.app',
    measurementId: 'G-KXD7N74ZHC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVeKdKIcvNjxIpXpDExQffkgKlEtVFAEg',
    appId: '1:259765583265:android:bd9bf6db55ee41980ddfe0',
    messagingSenderId: '259765583265',
    projectId: 'testdisc-1d691',
    storageBucket: 'testdisc-1d691.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPbYcN3gh4ASQzwLw9TmAZluSB1OQIVEw',
    appId: '1:259765583265:ios:ad8ff202cb242e760ddfe0',
    messagingSenderId: '259765583265',
    projectId: 'testdisc-1d691',
    storageBucket: 'testdisc-1d691.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiTesKepribadian',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPbYcN3gh4ASQzwLw9TmAZluSB1OQIVEw',
    appId: '1:259765583265:ios:ad8ff202cb242e760ddfe0',
    messagingSenderId: '259765583265',
    projectId: 'testdisc-1d691',
    storageBucket: 'testdisc-1d691.firebasestorage.app',
    iosBundleId: 'com.example.aplikasiTesKepribadian',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAbfUAjVzz0RkTbcrVyjVxgM6lEOdL5zi8',
    appId: '1:259765583265:web:ecd2792340ec60700ddfe0',
    messagingSenderId: '259765583265',
    projectId: 'testdisc-1d691',
    authDomain: 'testdisc-1d691.firebaseapp.com',
    storageBucket: 'testdisc-1d691.firebasestorage.app',
    measurementId: 'G-EGB78GSVL8',
  );
}
